on:
  pull_request:
    types:
      - closed

jobs:
  milestone_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to assign milestones to PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assign milestone to PR
        uses: ./
        id: assign-milestone
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          fallback: 'minor'
      - name: Show milestone
        run: echo "The milestone was set to ${{ steps.assign-milestone.outputs.milestone }}"
